### PR TITLE
Add Mock

### PR DESCRIPTION
**Pull request by JamesJeffryes**
This adds a mock Scale class with a matching interface for offline testing

### CODE REVIEW

**Comment by patrickfuller** [comment]
PR is good to go as is but can we take a minute to standardize our linters? I use flake8 and pydocstyle, where pydocstyle would yell at me for all of the docstrings.

I'm happy to change my linters as well if you feel strongly, but I figure flake8/pydocstyle are common standards.

**Comment by JamesJeffryes** [comment]
Should mocks have docstrings? It's yet another thing to become inconsistent

**Comment by patrickfuller** [comment]
I'm okay removing docstrings across all mocks if we can explicitly disable pydocstyle. Something like `# noqa pydocstyle` on the top line? idk if that works but there must be a way to do so, as there is for pycodestyle/mccabe/pyflakes within flake8

**Comment by patrickfuller** [comment]
You have been made an admin. Feel free to merge this and just let me know where else you need admin access.

**Comment by JamesJeffryes** [comment]
FWIW, There does not seem to be a way mark entire files as ignored in pydocstyle either as a toplevel config or in the file

**Comment by patrickfuller** [comment]
We could do a heavy handed `# flake8: noqa` on the top line of each mock file. It disables everything but I think that's okay for mocks.

**Pull request merged**
